# Generated by Django 2.2.5 on 2020-08-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=255)),
                ('file', models.FileField(blank=True, upload_to='%Y/%m/%d')),
                ('tag', models.CharField(default='NULL', max_length=255)),
                ('file_id', models.CharField(default='NULL', max_length=255)),
            ],
        ),
    ]
